### ISSUE TITLE
Old URLs are broken

### ISSUE THREAD

**Issue by dingens** [hukl/cccms#35] opened 2009-11-02 00:03 UTC
Check the URLs in the old feed: http://213.73.89.124/updates/chaosupdates.rdf

BTW: I think the old short urls are better anyway – Consider http://www.ccc.de/de/updates/2009/chaos-computer-club-verschenkt-spickzettel-digitaler-burgerrechte-fur-die-weiteren-koalitionsverhandlungen  ^^

Maybe this is not a bug in the software itself but only a migration issue – then please just close it here ;)

BTW: As I see in the code it is possible to change the slug – this is problematic as with the slug is the same as the ID in the feed. It should be possible to change it only before the entry is published, or the ID should be used for the feed ID (if you do something here, ignore me, I dont know ruby, I just saw `before_save   :check_for_changed_slug` ;) )

**Comment by hukl** [comment] 2009-11-03 19:04
hmm i think the slug won't be changed that often and mostly before publish - i have to tell the user after creating a node that they should check the slug or expose it more obvious. i think the slug should be changeable afterwards though it should be only done in exceptional situations. Maybe it should be prevented for updates. not sure. will look into it

**Comment by hukl** [comment] 2009-11-14 12:49
hmm the issue with the feed ids is the cause for the weird feed duplications. All new updates from now on will have an immutable entry id. Thanks for reporting took me a while to fully understand ;)

**Comment by hukl** [comment] 2009-11-14 12:51
Resolved issue of changing rss feed ids when changing the slugs of nodes

Closed by 713f8f76e2ae1635bb938de6d8c74587d842790f

**Closed as completed by hukl** 2009-11-14 12:51 UTC
Labels: UI, Behavior
